all: family_ugrad family_grad

family_ugrad: family_ugrad.cc
	g++ family_ugrad.cc -o family_ugrad

family_grad: family_grad.cc
	g++ family_grad.cc -o family_grad

clean:
	rm family_grad family_ugrad

.PHONY: clean
