#! /usr/bin/env python

import os
os.system("rm results/output_L_95.txt")
os.system("echo start")
os.system("N=1 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=2 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=3 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=4 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=5 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=6 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=7 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=8 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=9 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=10 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("echo 10")
os.system("N=11 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=12 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=13 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=14 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=15 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=16 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=17 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=18 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=19 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=20 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("echo 20")
os.system("N=21 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=22 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=23 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=24 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=25 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=26 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=27 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=28 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=29 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=30 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("echo 30")
os.system("N=31 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=32 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=33 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=34 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=35 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=36 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=37 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=38 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=39 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=40 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("echo 40")
os.system("N=41 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=42 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=43 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=44 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=45 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=46 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=47 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=48 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=49 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("N=50 && ./testa traindata/train_L_95 images/fb_L_images.txt ${N} >> results/output_L_95.txt")
os.system("echo complete")

